# natten: the package's own minimal GPU op, from
# packages/natten/package.yml `verify.op`. Generated by
# scripts/generate_recipes.py; edit package.yml, not this file.
import torch
import torch.nn.functional as F
from natten import na2d
torch.manual_seed(0)
B, H, W, heads, D = 1, 8, 8, 2, 32
q = torch.randn(B, H, W, heads, D, dtype=torch.float16, device="cuda")
k = torch.randn(B, H, W, heads, D, dtype=torch.float16, device="cuda")
v = torch.randn(B, H, W, heads, D, dtype=torch.float16, device="cuda")
out = na2d(q, k, v, kernel_size=(8, 8))
assert out.shape == q.shape, out.shape
qf = q.reshape(B, H * W, heads, D).transpose(1, 2)
kf = k.reshape(B, H * W, heads, D).transpose(1, 2)
vf = v.reshape(B, H * W, heads, D).transpose(1, 2)
ref = F.scaled_dot_product_attention(qf, kf, vf).transpose(1, 2).reshape(B, H, W, heads, D)
err = (out.float() - ref.float()).abs().max().item()
assert err < 0.05, f"na2d with a full-window kernel deviates from dense attention by {err}"
