# torchsparse: the package's own minimal GPU op, from
# packages/torchsparse/package.yml `verify.op`. Generated by
# scripts/generate_recipes.py; edit package.yml, not this file.
import torch, torchsparse
from torchsparse import SparseTensor
from torchsparse import nn as spnn
import torchsparse.nn.functional as F
torch.manual_seed(0)
coords = torch.unique(torch.randint(0, 8, (300, 3)), dim=0)
coords = torch.cat([coords, torch.zeros(coords.size(0), 1, dtype=coords.dtype)], 1).int()
n = coords.size(0)
h_gpu = F.sphash(coords.cuda())
h_cpu = F.sphash(coords)
assert (h_gpu.cpu() == h_cpu).all(), "hash_cuda disagrees with hash_cpu"
feats = torch.randn(n, 6, device="cuda")
x = SparseTensor(feats, coords.cuda())
conv = spnn.Conv3d(6, 5, kernel_size=1, bias=False).cuda()
y = conv(x)
ref = feats @ conv.kernel.view(6, 5)
assert torch.allclose(y.F, ref, atol=1e-4), (y.F - ref).abs().max()
conv3 = spnn.Conv3d(6, 5, kernel_size=3, bias=False).cuda()
y3 = conv3(x)
assert y3.F.shape == (n, 5) and torch.isfinite(y3.F).all()
# every output row must aggregate more than its own voxel somewhere:
# with 3^3 neighbourhoods on a dense-ish 8^3 grid, y3 != the centre-tap
# product alone proves the kernel map found neighbours
centre = feats @ conv3.kernel[13].view(6, 5)
assert not torch.allclose(y3.F, centre), "k=3 conv used only the centre tap"
