# nunchaku: the package's own minimal GPU op, from
# packages/nunchaku/package.yml `verify.op`. Generated by
# scripts/generate_recipes.py; edit package.yml, not this file.
import torch
from nunchaku.models.linear import AWQW4A16Linear
k, n, g = 128, 64, 64
torch.manual_seed(0)
lin = AWQW4A16Linear(k, n, bias=False, group_size=g, torch_dtype=torch.float16, device="cuda")
lin.qweight.data.zero_()
lin.wscales.data.fill_(1.0)
lin.wzeros.data.copy_(torch.randn(k // g, n, device="cuda", dtype=torch.float16))
x = torch.randn(1, k, device="cuda", dtype=torch.float16)
out = lin(x)
ref = x @ lin.wzeros.data.repeat_interleave(g, dim=0)
assert out.shape == (1, n), out.shape
err = (out.float() - ref.float()).abs().max().item()
assert err < 0.25, f"AWQ gemv deviates from the dense reference by {err}"
