# torch-sparse: the package's own minimal GPU op, from
# packages/torch-sparse/package.yml `verify.op`. Generated by
# scripts/generate_recipes.py; edit package.yml, not this file.
import torch
from torch_sparse import SparseTensor, matmul
d = torch.randn(64, 48, device="cuda")
d[torch.rand_like(d) < 0.7] = 0
b = torch.randn(48, 16, device="cuda")
A = SparseTensor.from_dense(d)
out = A @ b
assert torch.allclose(out, d @ b, atol=1e-4), (out - d @ b).abs().max()
out16 = matmul(A.to(torch.bfloat16), b.to(torch.bfloat16))
assert out16.dtype == torch.bfloat16
assert torch.allclose(out16.float(), d @ b, atol=0.5, rtol=0.1), (out16.float() - d @ b).abs().max()
# and a reduction kernel with a different code path
mx = matmul(A, b, reduce="max")
assert mx.shape == (64, 16) and torch.isfinite(mx).all()
