# sageattn3: the package's own minimal GPU op, from
# packages/sageattn3/package.yml `verify.op`. Generated by
# scripts/generate_recipes.py; edit package.yml, not this file.
import torch
import torch.nn.functional as F
cc = torch.cuda.get_device_capability()
assert cc[0] in (10, 12), (
    f"sageattn3 ships sm_100a/sm_120a only and this GPU is sm_{cc[0]}{cc[1]}: "
    f"the kernels cannot be exercised here -- verify on a Blackwell part")
from sageattn3 import sageattn3_blackwell
torch.manual_seed(0)
q = torch.randn(1, 4, 256, 128, dtype=torch.float16, device="cuda")
k = torch.randn(1, 4, 256, 128, dtype=torch.float16, device="cuda")
v = torch.randn(1, 4, 256, 128, dtype=torch.float16, device="cuda")
out = sageattn3_blackwell(q, k, v)
ref = F.scaled_dot_product_attention(q, k, v)
assert out.shape == ref.shape, out.shape
err = (out.float() - ref.float()).abs().max().item()
assert err < 0.2, f"sageattn3 deviates from SDPA by {err}"
