# diso: the package's own minimal GPU op, from
# packages/diso/package.yml `verify.op`. Generated by
# scripts/generate_recipes.py; edit package.yml, not this file.
import torch
from diso import DiffMC, DiffDMC
# A sphere SDF on a 32^3 grid; both extractors must produce a mesh, and
# the backward pass (the atomicAdd path) must run.
n = 32
ax = torch.linspace(-1, 1, n, device="cuda")
g = torch.stack(torch.meshgrid(ax, ax, ax, indexing="ij"), -1).norm(dim=-1) - 0.5
g = g.contiguous().requires_grad_(True)
v, f = DiffMC(dtype=torch.float32).cuda()(g, isovalue=0.0)
assert v.shape[0] > 100 and f.shape[1] == 3, (v.shape, f.shape)
v.sum().backward()
assert g.grad is not None and torch.isfinite(g.grad).all()
v2, f2 = DiffDMC(dtype=torch.float32).cuda()(g.detach(), isovalue=0.0)
assert v2.shape[0] > 100, v2.shape
