# diff-gaussian-rasterization: the package's own minimal GPU op, from
# packages/diff-gaussian-rasterization/package.yml `verify.op`. Generated by
# scripts/generate_recipes.py; edit package.yml, not this file.
import math, torch
from diff_gaussian_rasterization import GaussianRasterizationSettings, GaussianRasterizer
dev = "cuda"; H = W = 32
tanhalf = math.tan(math.radians(30))
znear, zfar = 0.01, 100.0
P = torch.zeros(4, 4)
P[0, 0] = 1 / tanhalf; P[1, 1] = 1 / tanhalf; P[3, 2] = 1.0
P[2, 2] = zfar / (zfar - znear); P[2, 3] = -(zfar * znear) / (zfar - znear)
view = torch.eye(4)
settings = GaussianRasterizationSettings(
    image_height=H, image_width=W, tanfovx=tanhalf, tanfovy=tanhalf,
    bg=torch.zeros(3, device=dev), scale_modifier=1.0,
    viewmatrix=view.T.contiguous().to(dev),
    projmatrix=(view.T @ P.T).contiguous().to(dev),
    sh_degree=0, campos=torch.zeros(3, device=dev), prefiltered=False, debug=False)
r = GaussianRasterizer(settings)
means3D = torch.tensor([[0.0, 0.0, 3.0]], device=dev)
means2D = torch.zeros(1, 3, device=dev)
color, radii, depth, alpha = r(
    means3D=means3D, means2D=means2D, opacities=torch.ones(1, 1, device=dev),
    colors_precomp=torch.tensor([[1.0, 0.5, 0.25]], device=dev),
    scales=torch.full((1, 3), 0.5, device=dev),
    rotations=torch.tensor([[1.0, 0.0, 0.0, 0.0]], device=dev))
torch.cuda.synchronize()
assert color.shape == (3, H, W), color.shape
assert torch.isfinite(color).all() and torch.isfinite(alpha).all()
assert int(radii[0]) > 0, radii
assert color[0].max() > 0.5, color[0].max()
assert alpha.max() > 0.5, alpha.max()
