# sageattention: the package's own minimal GPU op, from
# packages/sageattention/package.yml `verify.op`. Generated by
# scripts/generate_recipes.py; edit package.yml, not this file.
import torch
import torch.nn.functional as F
from sageattention import sageattn_qk_int8_pv_fp16_cuda
torch.manual_seed(0)
q = torch.randn(1, 4, 256, 64, dtype=torch.float16, device="cuda")
k = torch.randn(1, 4, 256, 64, dtype=torch.float16, device="cuda")
v = torch.randn(1, 4, 256, 64, dtype=torch.float16, device="cuda")
out = sageattn_qk_int8_pv_fp16_cuda(q, k, v, tensor_layout="HND", is_causal=False,
                                    pv_accum_dtype="fp32")
ref = F.scaled_dot_product_attention(q, k, v)
assert out.shape == ref.shape, out.shape
err = (out.float() - ref.float()).abs().max().item()
assert err < 0.1, f"sageattention deviates from SDPA by {err}"
