# nvdiffrast: the package's own minimal GPU op, from
# packages/nvdiffrast/package.yml `verify.op`. Generated by
# scripts/generate_recipes.py; edit package.yml, not this file.
import torch
import nvdiffrast.torch as dr
dev = "cuda"
glctx = dr.RasterizeCudaContext()
pos = torch.tensor([[[-0.8, -0.8, 0.0, 1.0], [0.8, -0.8, 0.0, 1.0],
                     [0.0, 0.8, 0.0, 1.0]]], device=dev)
tri = torch.tensor([[0, 1, 2]], dtype=torch.int32, device=dev)
rast, _ = dr.rasterize(glctx, pos, tri, resolution=[32, 32])
torch.cuda.synchronize()
assert rast.shape == (1, 32, 32, 4), rast.shape
cov = (rast[..., 3] > 0).float().mean().item()
assert 0.1 < cov < 0.9, cov
col = torch.tensor([[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]]], device=dev)
out, _ = dr.interpolate(col, rast, tri)
assert torch.isfinite(out).all() and out.max() > 0.5, out.max()
aa = dr.antialias(out, rast, pos, tri)
assert aa.shape == out.shape and torch.isfinite(aa).all()
