# flex-gemm: the package's own minimal GPU op, from
# packages/flex-gemm/package.yml `verify.op`. Generated by
# scripts/generate_recipes.py; edit package.yml, not this file.
import torch
from flex_gemm.ops.serialize import encode_seq
coords = torch.stack(torch.meshgrid(torch.arange(2), torch.arange(4), torch.arange(4),
                                    torch.arange(4), indexing="ij"), -1).reshape(-1, 4).int()
shape = torch.Size([2, 8, 4, 4, 4])
on_gpu = encode_seq(coords.cuda(), shape, "z_order").cpu()
on_cpu = encode_seq(coords, shape, "z_order")
assert torch.equal(on_gpu, on_cpu), (on_gpu[:8], on_cpu[:8])
assert on_gpu.unique().numel() == coords.shape[0], "codes are not a bijection"
