# cc-torch: the package's own minimal GPU op, from
# packages/cc-torch/package.yml `verify.op`. Generated by
# scripts/generate_recipes.py; edit package.yml, not this file.
import torch, cc_torch
x = torch.zeros(1, 1, 16, 16, dtype=torch.uint8, device="cuda")
x[0, 0, 2:6, 2:6] = 255
labels, counts = cc_torch.get_connected_components(x)
assert labels.shape == x.shape, labels.shape
# background plus exactly one blob: proves the kernel actually labelled
# rather than returning zeros, so a mis-arch'd build fails here with
# cudaErrorNoKernelImageForDevice instead of passing a bare import.
assert labels.unique().numel() == 2, labels.unique()
