# o-voxel-vb: the package's own minimal GPU op, from
# packages/o-voxel-vb/package.yml `verify.op`. Generated by
# scripts/generate_recipes.py; edit package.yml, not this file.
import torch, o_voxel_vb as o_voxel
from o_voxel_vb.serialize import encode_seq, decode_seq
c = torch.randint(0, 1024, (4096, 3), device="cuda", dtype=torch.int32)
for mode in ("z_order", "hilbert"):
    code = encode_seq(c, mode=mode)
    back = decode_seq(code, mode=mode)
    assert torch.equal(back.int(), c), mode
from o_voxel_vb.convert.flexible_dual_grid import _init_hashmap
n, grid = 512, torch.tensor([64, 64, 64])
coords = torch.stack(torch.meshgrid(*[torch.arange(8)] * 3, indexing="ij"), -1).reshape(-1, 3).int().cuda()
keys = torch.cat([torch.zeros_like(coords[:, :1]), coords], dim=-1)
hm = _init_hashmap(grid, 2 * n, device="cuda")
o_voxel._C.hashmap_insert_3d_idx_as_val_cuda(*hm, keys, *grid.tolist())
got = o_voxel._C.hashmap_lookup_3d_cuda(*hm, keys, *grid.tolist())
assert torch.equal(got.int().cpu(), torch.arange(n, dtype=torch.int32)), got[:8]
