# dpvo-cuda: the package's own minimal GPU op, from
# packages/dpvo-cuda/package.yml `verify.op`. Generated by
# scripts/generate_recipes.py; edit package.yml, not this file.
import torch, cuda_corr, cuda_ba, lietorch_backends
import dpvo.lietorch.broadcasting, dpvo.lietorch.gradcheck, dpvo.lietorch.group_ops
import dpvo.altcorr.correlation, dpvo.fastba.ba
from dpvo.lietorch import SE3
# lietorch_backends: SE3 exp then log on the GPU must round-trip.
x = 0.1 * torch.randn(16, 6, device="cuda")
g = SE3.exp(x)
y = g.log()
assert torch.allclose(x, y, atol=1e-4), (x - y).abs().max()
# cuda_corr: patchify a feature map at integer coords, radius 1.
net = torch.arange(1 * 2 * 8 * 8, dtype=torch.float32, device="cuda").view(1, 2, 8, 8)
coords = torch.tensor([[[3.0, 4.0]]], device="cuda")   # [B=1, M=1, 2] (x, y)
(patches,) = cuda_corr.patchify_forward(net, coords, 1)
assert patches.shape == (1, 1, 2, 4, 4), patches.shape
assert patches[0, 0, 0, 1, 1].item() == net[0, 0, 4, 3].item(), patches[0, 0, 0]
# cuda_ba: reproject one patch between two identity poses; the kernel
# must hand back the patch's own pixel coordinates.
poses = torch.tensor([[0, 0, 0, 0, 0, 0, 1.0]] * 2, device="cuda")          # [F, 7] t + unit quaternion
patches = torch.zeros(1, 3, 3, 3, device="cuda")                               # [M, (x, y, inv depth), P, P]
patches[0, 0], patches[0, 1], patches[0, 2] = 10.0, 20.0, 0.5
intr = torch.tensor([[100.0, 100.0, 50.0, 50.0]], device="cuda")             # fx fy cx cy
idx = lambda v: torch.tensor([v], dtype=torch.long, device="cuda")
coords = cuda_ba.reproject(poses, patches, intr, idx(0), idx(1), idx(0))     # [1, N, 2, P, P]
assert coords.shape == (1, 1, 2, 3, 3), coords.shape
assert torch.allclose(coords[0, 0, 0], torch.full((3, 3), 10.0, device="cuda"), atol=1e-3), coords
assert torch.allclose(coords[0, 0, 1], torch.full((3, 3), 20.0, device="cuda"), atol=1e-3), coords
