# torchaudio: the package's own minimal GPU op, from
# packages/torchaudio/package.yml `verify.op`. Generated by
# scripts/generate_recipes.py; edit package.yml, not this file.
import torch, torchaudio
import torchaudio.functional as F
import torchaudio.transforms, torchaudio.io
x = torch.randn(1, 16000, device="cuda")
y = F.resample(x, 16000, 8000)
assert y.shape[-1] == 8000, y.shape
assert torch.isfinite(y).all()
a = torch.tensor([1.0, -0.5], device="cuda")
b = torch.tensor([0.5, 0.5], device="cuda")
z = F.lfilter(x, a, b)
assert z.shape == x.shape and torch.isfinite(z).all()
# Fail closed on the backends. Both are ON by default upstream and both
# reach the network to build, so the tempting fix is to switch them off
# -- which builds cleanly, passes every check above, and ships a package
# missing what upstream's own wheel carries. Exactly the torchvision
# codec trap, so it is asserted rather than assumed. These are the two
# libraries that only exist if sox and ffmpeg were really compiled.
import os, glob, torio, torchaudio.lib as _lib
_libs = {os.path.basename(p) for p in glob.glob(os.path.dirname(_lib.__file__) + "/*.so")}
_libs |= {os.path.basename(p) for p in glob.glob(os.path.dirname(torio.__file__) + "/lib/*.so")}
# What can silently REGRESS is whether the backend was BUILT -- switch
# BUILD_SOX or USE_FFMPEG off and these libraries simply do not exist.
# Whether one can LOAD is a property of the machine, not the build: the
# conda package declares ffmpeg and sox so it always can, while the wheel
# deliberately vendors neither (upstream's does not either) and therefore
# cannot on a host without them. Asserting existence holds for both.
assert "libtorchaudio_sox.so" in _libs, sorted(_libs)
assert "libtorio_ffmpeg.so" in _libs, sorted(_libs)
# And where ffmpeg IS present, the extension must actually work. Note
# lazy_import_ffmpeg_ext() returns a _LazyImporter that is NEVER None --
# asserting "is not None" passes even when no ffmpeg exists anywhere,
# which is how an earlier version of this op reported a working backend
# in a venv that had none. is_available() is the real probe.
from torio._extension import lazy_import_ffmpeg_ext
import ctypes.util
# Both backends BY NAME through torchaudio's own registry -- upstream's
# statement that the extension loaded, not a file existing on disk.
# Each is required wherever its library is present: always in the conda
# env (ffmpeg and sox are run deps there), and in a venv only if the host
# happens to have them, since the wheel vendors neither.
backends = set(torchaudio.list_audio_backends())
if ctypes.util.find_library("avutil"):
    assert lazy_import_ffmpeg_ext().is_available(), \
        "ffmpeg is installed but torio's extension will not load"
    assert "ffmpeg" in backends, backends
if ctypes.util.find_library("sox"):
    assert "sox" in backends, backends
