# mmcv: the package's own minimal GPU op, from
# packages/mmcv/package.yml `verify.op`. Generated by
# scripts/generate_recipes.py; edit package.yml, not this file.
import torch, mmcv
import mmcv.runner, mmcv.cnn
from mmcv.ops import nms, roi_align
boxes = torch.tensor([[0., 0., 10., 10.], [1., 1., 11., 11.], [50., 50., 60., 60.]],
                     device="cuda")
scores = torch.tensor([0.9, 0.8, 0.7], device="cuda")
dets, keep = nms(boxes, scores, 0.5)
assert keep.numel() == 2, keep
feat = torch.arange(64., device="cuda").view(1, 1, 8, 8)
rois = torch.tensor([[0., 0., 0., 4., 4.]], device="cuda")
out = roi_align(feat, rois, (2, 2), 1.0, 2, "avg", True)
assert out.shape == (1, 1, 2, 2) and torch.isfinite(out).all(), out
# Config.pretty_text is the yapf-at-import path -- the reason yapf is a
# runtime dep and not a build tool here.
assert "a=1" in mmcv.Config(dict(a=1)).pretty_text.replace(" ", "")
