# nvdiffrec-render: the package's own minimal GPU op, from
# packages/nvdiffrec-render/package.yml `verify.op`. Generated by
# scripts/generate_recipes.py; edit package.yml, not this file.
import math, torch
import nvdiffrec_render.renderutils as ru
dev = "cuda"
pts = torch.rand(1, 64, 3, device=dev)
m = torch.eye(4, device=dev)[None].clone()
m[0, :3, 3] = torch.tensor([1.0, 2.0, 3.0], device=dev)
out = ru.xfm_points(pts, m)
torch.cuda.synchronize()
ref = ru.xfm_points(pts, m, use_python=True)
assert out.shape == (1, 64, 4), out.shape
assert torch.isfinite(out).all() and torch.allclose(out, ref, atol=1e-5), (out - ref).abs().max()
nrm = torch.tensor([0.0, 0.0, 1.0], device=dev).view(1, 1, 1, 3).expand(1, 4, 4, 3)
wi = torch.nn.functional.normalize(torch.tensor([0.0, 1.0, 1.0], device=dev), dim=0).view(1, 1, 1, 3).expand(1, 4, 4, 3)
lam = ru.lambert(nrm.contiguous(), wi.contiguous())
torch.cuda.synchronize()
assert lam.shape == (1, 4, 4, 1), lam.shape
assert torch.allclose(lam, torch.full_like(lam, math.sqrt(0.5) / math.pi), atol=1e-5), lam.flatten()[:4]
