# torchvision: the package's own minimal GPU op, from
# packages/torchvision/package.yml `verify.op`. Generated by
# scripts/generate_recipes.py; edit package.yml, not this file.
import torch, torchvision, io
from torchvision.ops import nms
boxes = torch.tensor([[0., 0., 10., 10.], [1., 1., 11., 11.], [50., 50., 60., 60.]],
                     device="cuda")
scores = torch.tensor([0.9, 0.8, 0.7], device="cuda")
keep = nms(boxes, scores, 0.5)
assert keep.numel() == 2, keep
from torchvision.io import decode_jpeg, encode_jpeg, decode_png, encode_png, decode_image
img = (torch.rand(3, 32, 32) * 255).to(torch.uint8)
assert decode_jpeg(encode_jpeg(img)).shape == img.shape
assert decode_png(encode_png(img)).shape == img.shape
# webp: the reason libwebp-base is a host dep. Pillow encodes (torchvision
# has no webp encoder); torchvision's own decode_webp -- a public API from
# 0.20 (torch 2.5); 0.19 links libwebp but exposes no decoder -- must read
# it back, bit-exact since the encode is lossless.
from PIL import Image, features
if hasattr(torchvision.io, "decode_webp"):
    buf = io.BytesIO()
    Image.fromarray(img.permute(1, 2, 0).numpy()).save(buf, format="WEBP", lossless=True)
    w = torchvision.io.decode_webp(torch.frombuffer(buf.getvalue(), dtype=torch.uint8))
    assert w.shape == img.shape and torch.equal(w, img), w.shape
# nvjpeg path: the reason libnvjpeg-dev is a host dep
d = decode_jpeg(encode_jpeg(img), device="cuda")
assert d.is_cuda and d.shape == img.shape, d.shape
# avif, wherever the extra decoders are present (torchvision >= 0.20,
# torchvision-extra-decoders installed, and a Pillow that can encode it).
import importlib.util
if (importlib.util.find_spec("torchvision_extra_decoders")
        and hasattr(torchvision.io, "decode_avif") and features.check("avif")):
    buf = io.BytesIO()
    Image.fromarray(img.permute(1, 2, 0).numpy()).save(buf, format="AVIF")
    a = torchvision.io.decode_avif(torch.frombuffer(buf.getvalue(), dtype=torch.uint8))
    assert a.shape == img.shape, a.shape
