# torch-cluster: the package's own minimal GPU op, from
# packages/torch-cluster/package.yml `verify.op`. Generated by
# scripts/generate_recipes.py; edit package.yml, not this file.
import torch
from torch_cluster import knn, fps, radius
x = torch.randn(300, 3, device="cuda")
y = torch.randn(40, 3, device="cuda")
k = 5
row, col = knn(x, y, k)               # row: index into y, col: index into x
ref = torch.cdist(y, x).topk(k, largest=False).indices    # [40, k]
got = torch.zeros_like(ref)
got[row, torch.arange(k, device="cuda").repeat(40)] = col   # each y has exactly k rows
assert (got.sort(1).values == ref.sort(1).values).all(), "knn disagrees with cdist"
row16, col16 = knn(x.bfloat16(), y.bfloat16(), k)
assert row16.numel() == 40 * k, row16.numel()
idx = fps(x, ratio=0.25, random_start=False)
assert idx.numel() == 75 and idx.unique().numel() == 75, idx.numel()
r_row, r_col = radius(x, y, 0.5, max_num_neighbors=64)
d = (y[r_row] - x[r_col]).norm(dim=1)
assert (d <= 0.5 + 1e-5).all(), d.max()
