# cumesh-vb: the package's own minimal GPU op, from
# packages/cumesh-vb/package.yml `verify.op`. Generated by
# scripts/generate_recipes.py; edit package.yml, not this file.
import torch, cumesh_vb as cumesh
v = torch.tensor([[x, y, z] for x in (0, 1) for y in (0, 1) for z in (0, 1)], dtype=torch.float32, device="cuda")
f = torch.tensor([[0,1,3],[0,3,2],[4,6,7],[4,7,5],[0,4,5],[0,5,1],
                  [2,3,7],[2,7,6],[0,2,6],[0,6,4],[1,5,7],[1,7,3]], dtype=torch.int32, device="cuda")
m = cumesh.CuMesh()
m.init(v, f)
m.remove_duplicate_faces()
v2, f2 = m.read()
assert v2.shape == (8, 3) and f2.shape == (12, 3), (v2.shape, f2.shape)
bvh = cumesh.cuBVH(v, f)
d, _, _ = bvh.unsigned_distance(torch.tensor([[0.5, 0.5, 0.5]], device="cuda"), return_uvw=False)
assert abs(d.item() - 0.5) < 1e-4, d
