# flex-gemm-vb: the package's own minimal GPU op, from
# packages/flex-gemm-vb/package.yml `verify.op`. Generated by
# scripts/generate_recipes.py; edit package.yml, not this file.
import torch, flex_gemm_vb
from flex_gemm_vb.ops.serialize import encode_seq, decode_seq
# [N, 4] batch-prefixed coords, the CUDA z-order / Hilbert kernels.
c = torch.randint(0, 64, (4096, 3), device="cuda", dtype=torch.int32)
c = torch.cat([torch.zeros_like(c[:, :1]), c], dim=1)
shape = torch.Size([1, 8, 64, 64, 64])
for mode in ("z_order", "hilbert"):
    code = encode_seq(c, shape, mode=mode)
    back = decode_seq(code, shape, mode=mode)
    assert torch.equal(back[:, 1:].int(), c[:, 1:]), mode
