# detectron2: the package's own minimal GPU op, from
# packages/detectron2/package.yml `verify.op`. Generated by
# scripts/generate_recipes.py; edit package.yml, not this file.
import torch
import detectron2.engine, detectron2.data, detectron2.model_zoo
import detectron2.utils.visualizer
from detectron2.data.transforms import ExtentTransform   # the Image.LINEAR site
from detectron2.layers import nms_rotated
boxes = torch.tensor([[10., 10., 20., 20., 0.], [10., 10., 20., 20., 5.],
                      [60., 60., 10., 10., 0.]], device="cuda")
scores = torch.tensor([0.9, 0.8, 0.7], device="cuda")
keep = nms_rotated(boxes, scores, 0.5)
assert keep.numel() == 2, keep
# and the other big kernel family, deformable conv (csrc/deformable/)
from detectron2.layers import DeformConv
conv = DeformConv(4, 4, kernel_size=3, padding=1).cuda()
x = torch.randn(1, 4, 8, 8, device="cuda")
offset = torch.zeros(1, 18, 8, 8, device="cuda")
y = conv(x, offset)
assert y.shape == x.shape and torch.isfinite(y).all(), y.shape
