# torch-scatter: the package's own minimal GPU op, from
# packages/torch-scatter/package.yml `verify.op`. Generated by
# scripts/generate_recipes.py; edit package.yml, not this file.
import torch, torch_scatter
src = torch.randn(200, 8, device="cuda")
idx = torch.randint(0, 16, (200,), device="cuda")
out, arg = torch_scatter.scatter_max(src, idx, dim=0, dim_size=16)
ref = torch.full((16, 8), float("-inf"), device="cuda").scatter_reduce(
    0, idx.unsqueeze(-1).expand_as(src), src, "amax", include_self=False)
ref[torch.isinf(ref)] = 0
assert torch.allclose(out, ref), (out - ref).abs().max()
# arg indexes the winning row per (segment, column); empty segments get dim_size
filled = ref != 0
picked = src.gather(0, arg.clamp(max=src.size(0) - 1))
assert (picked[filled] == out[filled]).all(), "scatter_max argmax does not point at the max"
# segment_csr: sum over CSR segments, against a cumsum reference
x = torch.randn(64, 4, device="cuda")
ptr = torch.tensor([0, 10, 25, 25, 64], device="cuda")
seg = torch_scatter.segment_csr(x, ptr, reduce="sum")
ref2 = torch.stack([x[a:b].sum(0) for a, b in zip(ptr[:-1].tolist(), ptr[1:].tolist())])
assert torch.allclose(seg, ref2, atol=1e-4), (seg - ref2).abs().max()
