# gsplat-maskgaussian: the package's own minimal GPU op, from
# packages/gsplat-maskgaussian/package.yml `verify.op`. Generated by
# scripts/generate_recipes.py; edit package.yml, not this file.
import math, torch, gsplat
dev = "cuda"
means = torch.tensor([[0.0, 0.0, 3.0]], device=dev)
quats = torch.tensor([[1.0, 0.0, 0.0, 0.0]], device=dev)
scales = torch.full((1, 3), 0.5, device=dev)
opacities = torch.tensor([1.0], device=dev)
colors = torch.tensor([[1.0, 0.5, 0.25]], device=dev)
viewmats = torch.eye(4, device=dev)[None]
W = H = 32
f = W / (2 * math.tan(math.radians(30)))
Ks = torch.tensor([[[f, 0, W / 2], [0, f, H / 2], [0, 0, 1]]], device=dev)
img, alpha, meta = gsplat.rasterization(means, quats, scales, opacities,
                                        colors, viewmats, Ks, W, H,
                                        render_mode="RGB+D", distloss=True)
torch.cuda.synchronize()
# RGB + depth; the fork's two distortion channels are consumed into
# meta["render_distort"], which vanilla gsplat never produces.
assert img.shape == (1, H, W, 4), img.shape
assert "render_distort" in meta, sorted(meta)
assert torch.isfinite(img).all() and torch.isfinite(alpha).all()
assert alpha.max() > 0.5, alpha.max()
assert img[..., 0].max() > 0.5, img[..., 0].max()
assert img[..., 3].max() > 1.0, img[..., 3].max()   # depth of a splat at z=3
