# cubvh: the package's own minimal GPU op, from
# packages/cubvh/package.yml `verify.op`. Generated by
# scripts/generate_recipes.py; edit package.yml, not this file.
import numpy as np, torch, cubvh
# A unit cube: 8 vertices, 12 triangles (the BVH refuses < 9 triangles).
v = np.array([[x, y, z] for x in (0, 1) for y in (0, 1) for z in (0, 1)], dtype=np.float32)
f = np.array([[0,1,3],[0,3,2],[4,6,7],[4,7,5],[0,4,5],[0,5,1],
              [2,3,7],[2,7,6],[0,2,6],[0,6,4],[1,5,7],[1,7,3]], dtype=np.int32)
bvh = cubvh.cuBVH(v, f)
q = torch.tensor([[0.5, 0.5, 0.5], [2.0, 0.5, 0.5]], device="cuda")
d, fid, _ = bvh.unsigned_distance(q, return_uvw=False)
assert torch.allclose(d.cpu(), torch.tensor([0.5, 1.0]), atol=1e-4), d
