# drtk: the package's own minimal GPU op, from
# packages/drtk/package.yml `verify.op`. Generated by
# scripts/generate_recipes.py; edit package.yml, not this file.
import torch, drtk
dev = "cuda"; H = W = 32
v = torch.tensor([[[2.0, 2.0, 1.0], [29.0, 2.0, 1.0], [15.0, 29.0, 1.0]]], device=dev)
vi = torch.tensor([[0, 1, 2]], dtype=torch.int32, device=dev)
idx = drtk.rasterize(v, vi, H, W)
torch.cuda.synchronize()
assert idx.shape == (1, H, W) and idx.dtype == torch.int32, (idx.shape, idx.dtype)
cov = (idx >= 0).float().mean().item()
assert 0.2 < cov < 0.8, cov
depth, bary = drtk.render(v, vi, idx)
torch.cuda.synchronize()
# [N, 3, H, W] -- what the kernel returns; upstream's docstring says
# [N, H, W, 3] and is wrong (measured on the built artifact).
assert bary.shape == (1, 3, H, W), bary.shape
hit = idx >= 0
b = bary[0].permute(1, 2, 0)[hit[0]]
assert torch.isfinite(b).all()
assert torch.allclose(b.sum(-1), torch.ones(int(hit.sum()), device=dev), atol=1e-4)
assert torch.allclose(depth[hit], torch.ones(int(hit.sum()), device=dev), atol=1e-4)
