# torch-spline-conv: the package's own minimal GPU op, from
# packages/torch-spline-conv/package.yml `verify.op`. Generated by
# scripts/generate_recipes.py; edit package.yml, not this file.
import torch
from torch_spline_conv import spline_basis, spline_weighting
E, D, Min, Mout = 128, 2, 8, 4
pseudo = torch.rand(E, D)
kernel_size = torch.tensor([5, 5])
is_open = torch.tensor([1, 0], dtype=torch.uint8)
x = torch.randn(E, Min)
w = torch.randn(25, Min, Mout)
b_cpu, i_cpu = spline_basis(pseudo, kernel_size, is_open, 1)
b_gpu, i_gpu = spline_basis(pseudo.cuda(), kernel_size.cuda(), is_open.cuda(), 1)
assert torch.allclose(b_gpu.cpu(), b_cpu, atol=1e-5), (b_gpu.cpu() - b_cpu).abs().max()
assert (i_gpu.cpu() == i_cpu).all()
y_cpu = spline_weighting(x, w, b_cpu, i_cpu)
y_gpu = spline_weighting(x.cuda(), w.cuda(), b_gpu, i_gpu)
assert y_gpu.shape == (E, Mout)
assert torch.allclose(y_gpu.cpu(), y_cpu, atol=1e-4), (y_gpu.cpu() - y_cpu).abs().max()
