# custom-rasterizer-hy3d2: the package's own minimal GPU op, from
# packages/custom-rasterizer-hy3d2/package.yml `verify.op`. Generated by
# scripts/generate_recipes.py; edit package.yml, not this file.
import torch
import custom_rasterizer_kernel as crk
dev = "cuda"; H = W = 32
V = torch.tensor([[-0.8, -0.8, 0.5, 1.0], [0.8, -0.8, 0.5, 1.0],
                  [0.0, 0.8, 0.5, 1.0]], device=dev)
F = torch.tensor([[0, 1, 2]], dtype=torch.int32, device=dev)
findices, bary = crk.rasterize_image(V, F, torch.zeros(0, device=dev), W, H, 1e-6, 0)
torch.cuda.synchronize()
assert findices.shape == (H, W) and bary.shape == (H, W, 3), (findices.shape, bary.shape)
hit = findices > 0
cov = hit.float().mean().item()
assert 0.1 < cov < 0.9, cov
assert int(findices.max()) == 1, findices.max()
assert torch.isfinite(bary).all()
assert torch.allclose(bary[hit].sum(-1), torch.ones(int(hit.sum()), device=dev), atol=1e-4)
