# fused-ssim: the package's own minimal GPU op, from
# packages/fused-ssim/package.yml `verify.op`. Generated by
# scripts/generate_recipes.py; edit package.yml, not this file.
import torch, fused_ssim
a = torch.rand(1, 3, 32, 32, device="cuda")
b = torch.rand(1, 3, 32, 32, device="cuda")
v = fused_ssim.fused_ssim(a, b)
assert torch.isfinite(v).all(), v
