# torchao: the package's own minimal GPU op, from
# packages/torchao/package.yml `verify.op`. Generated by
# scripts/generate_recipes.py; edit package.yml, not this file.
import torch, torchao, torchao.ops
N, K, inner_k_tiles = 256, 256, 2
t = torch.randint(0, 16, dtype=torch.int, size=(N, K), device="cuda")
packed = torch.ops.aten._convert_weight_to_int4pack(
    (t[:, ::2] << 4 | t[:, 1::2]).to(torch.uint8), inner_k_tiles)
unpacked = torchao.ops.unpack_tensor_core_tiled_layout(packed, inner_k_tiles)
assert unpacked.shape == (N, K) and torch.equal(unpacked, t)
# and the high-level API on top of it
from torchao.quantization import quantize_, Int8WeightOnlyConfig
m = torch.nn.Linear(64, 64).cuda().bfloat16()
quantize_(m, Int8WeightOnlyConfig())
y = m(torch.randn(2, 64, device="cuda", dtype=torch.bfloat16))
assert y.shape == (2, 64) and torch.isfinite(y).all()
