# pytorch3d: the package's own minimal GPU op, from
# packages/pytorch3d/package.yml `verify.op`. Generated by
# scripts/generate_recipes.py; edit package.yml, not this file.
import torch
import pytorch3d.io
from pytorch3d.ops import knn_points
p1 = torch.randn(1, 64, 3, device="cuda")
p2 = torch.randn(1, 128, 3, device="cuda")
dists, idx, _ = knn_points(p1, p2, K=4)
assert idx.shape == (1, 64, 4), idx.shape
ref = torch.cdist(p1, p2).topk(4, largest=False).indices
assert torch.equal(idx.sort(dim=-1).values, ref.sort(dim=-1).values)
# and a second kernel family: the mesh rasterizer
from pytorch3d.structures import Meshes
from pytorch3d.renderer import rasterize_meshes
verts = torch.tensor([[-1., -1., 1.], [1., -1., 1.], [0., 1., 1.]], device="cuda")
faces = torch.tensor([[0, 1, 2]], device="cuda")
pix, zbuf, bary, dist = rasterize_meshes(Meshes([verts], [faces]), image_size=16, faces_per_pixel=1)
assert (pix >= 0).any(), "rasterizer covered no pixel"
