# faithc-aot: the package's own minimal GPU op, from
# packages/faithc-aot/package.yml `verify.op`. Generated by
# scripts/generate_recipes.py; edit package.yml, not this file.
import torch
from atom3d.kernels import get_cuda_kernels, ray_mesh_intersect, point_mesh_udf
from atom3d.kernels.bvh import get_bvh_kernels, BVHAccelerator
from atom3d.kernels.flood_fill import get_floodfill_kernels
for mod, name in ((get_cuda_kernels(), "cumtv_cuda"), (get_bvh_kernels(), "bvh_cuda"),
                  (get_floodfill_kernels(), "floodfill_cuda")):
    assert mod.__name__ == f"atom3d.kernels.{name}", (mod.__name__, mod.__file__)
dev = "cuda"
verts = torch.tensor([[0.0, 0.0, 0.0], [1.0, 0.0, 0.0], [0.0, 1.0, 0.0]], device=dev)
faces = torch.tensor([[0, 1, 2]], dtype=torch.int32, device=dev)
rays_o = torch.tensor([[0.2, 0.2, 1.0], [2.0, 2.0, 1.0]], device=dev)
rays_d = torch.tensor([[0.0, 0.0, -1.0], [0.0, 0.0, -1.0]], device=dev)
hit, t, fid, pts, uv = ray_mesh_intersect(verts, faces, rays_o, rays_d)
torch.cuda.synchronize()
assert hit.tolist() == [True, False], hit
assert abs(t[0].item() - 1.0) < 1e-5, t
d, cf, cp, uvw = point_mesh_udf(verts, faces, torch.tensor([[0.2, 0.2, 0.5]], device=dev))
assert abs(d[0].item() - 0.5) < 1e-5, d
bvh = BVHAccelerator(verts, faces)
hit2, t2, fid2, pts2 = bvh.ray_intersect(rays_o, rays_d)
torch.cuda.synchronize()
assert hit2.tolist() == [True, False] and abs(t2[0].item() - 1.0) < 1e-5, (hit2, t2)
