# spconv: the package's own minimal GPU op, from
# packages/spconv/package.yml `verify.op`. Generated by
# scripts/generate_recipes.py; edit package.yml, not this file.
import torch, torch.nn.functional as F
import spconv.pytorch as spconv
torch.manual_seed(0)
D = 8
coords = torch.unique(torch.randint(0, D, (300, 3)), dim=0)
n = coords.size(0)
bidx = torch.zeros(n, 1, dtype=coords.dtype)
coords_b = torch.cat([bidx, coords], 1).int().cuda()      # [batch, z, y, x]
feats = torch.randn(n, 4, device="cuda")
x = spconv.SparseConvTensor(feats, coords_b, [D, D, D], 1)
dense_in = x.dense()                                        # [1, 4, D, D, D]
conv = spconv.SparseConv3d(4, 5, 3, padding=1, bias=False).cuda()
y3 = conv(x)
w = conv.weight.permute(0, 4, 1, 2, 3).contiguous()         # [out, k, k, k, in] -> [out, in, k, k, k]
dense_ref = F.conv3d(dense_in, w, padding=1)
got = y3.dense()
assert got.shape == dense_ref.shape, (got.shape, dense_ref.shape)
assert torch.allclose(got, dense_ref, atol=1e-3), (got - dense_ref).abs().max()
sub = spconv.SubMConv3d(4, 5, 3, bias=False).cuda()
ys = sub(x)
assert torch.equal(ys.indices, x.indices), "submanifold conv must keep the input coordinates"
ws = sub.weight.permute(0, 4, 1, 2, 3).contiguous()
occ = (dense_in.abs().sum(1, keepdim=True) > 0).float()
sub_ref = F.conv3d(dense_in, ws, padding=1) * occ
assert torch.allclose(ys.dense(), sub_ref, atol=1e-3), (ys.dense() - sub_ref).abs().max()
