# spconv: the package's own minimal GPU op, from
# packages/spconv/package.yml `verify.op`. Generated by
# scripts/generate_recipes.py; edit package.yml, not this file.
import numpy as np
from cumm import tensorview as tv
import spconv
from spconv.utils import Point2VoxelGPU3d
from spconv.algo import GEMM
from spconv.core import AlgoHint
from cumm.gemm.algospec.core import ShuffleStrideType
arch = tv.get_compute_capability()
rng = np.random.default_rng(0)
pc = rng.uniform(-0.99, 0.99, (4096, 3)).astype(np.float32)
gen = Point2VoxelGPU3d(vsize_xyz=[0.25, 0.25, 0.25], coors_range_xyz=[-1, -1, -1, 1, 1, 1],
                       num_point_features=3, max_num_voxels=10000, max_num_points_per_voxel=1)
voxels, coords, num_pts = gen.point_to_voxel_hash(tv.from_numpy(pc).cuda())
got = np.unique(coords.cpu().numpy()[:, ::-1], axis=0)         # zyx -> xyz
ref = np.unique(np.floor((pc + 1.0) / 0.25).astype(np.int32), axis=0)
assert got.shape == ref.shape and np.array_equal(got, ref), (got.shape, ref.shape)
M, K, N = 256, 64, 96
a_np = rng.standard_normal((M, K)).astype(np.float32)
b_np = rng.standard_normal((N, K)).astype(np.float32)   # KC layout: trans_b
perm = rng.permutation(M).astype(np.int32)
ident = np.arange(M, dtype=np.int32)
c_np = np.zeros((M, N), np.float32)
a, b, c = tv.from_numpy(a_np).cuda(), tv.from_numpy(b_np).cuda(), tv.from_numpy(c_np).cuda()
a_inds, c_inds = tv.from_numpy(perm).cuda(), tv.from_numpy(ident).cuda()
kw = dict(shuffle_type=ShuffleStrideType.ShuffleAC, a_inds=a_inds, c_inds=c_inds,
          hint=AlgoHint.Fowrard.value)
res, _ = GEMM.tune_and_cache(a, b, c, False, True, False, arch=arch, use_tf32=False, **kw)
desp = GEMM.run_with_tuned_result(res, a, b, c, False, True, False, arch=arch, stream=0, **kw)
GEMM.device_synchronize()
out = c.cpu().numpy()
ref2 = a_np[perm] @ b_np.T
assert np.allclose(out, ref2, atol=1e-3), (str(desp), np.abs(out - ref2).max())
