# pointnet2-ops: the package's own minimal GPU op, from
# packages/pointnet2-ops/package.yml `verify.op`. Generated by
# scripts/generate_recipes.py; edit package.yml, not this file.
import os, torch, pointnet2_ops
from pointnet2_ops import pointnet2_utils as U
assert U._ext.__name__ == "pointnet2_ops._ext", U._ext
assert os.path.dirname(U._ext.__file__) == os.path.dirname(pointnet2_ops.__file__), U._ext.__file__
torch.manual_seed(0)
known = torch.rand(2, 50, 3, device="cuda")
unknown = torch.rand(2, 20, 3, device="cuda")
dist, idx = U.three_nn(unknown, known)
ref_d, ref_i = torch.cdist(unknown, known).topk(3, dim=-1, largest=False)
assert (idx == ref_i).all(), "three_nn indices disagree with cdist"
assert torch.allclose(dist, ref_d, atol=1e-4), (dist - ref_d).abs().max()
xyz = torch.rand(1, 64, 3, device="cuda")
got = U.furthest_point_sample(xyz, 8)[0].tolist()
pts, picked, mind = xyz[0], [0], torch.full((64,), float("inf"), device="cuda")
for _ in range(7):
    mind = torch.minimum(mind, ((pts - pts[picked[-1]]) ** 2).sum(-1))
    picked.append(int(mind.argmax()))
assert got == picked, (got, picked)
