# simple-knn: the package's own minimal GPU op, from
# packages/simple-knn/package.yml `verify.op`. Generated by
# scripts/generate_recipes.py; edit package.yml, not this file.
import torch
from simple_knn._C import distCUDA2
g = torch.arange(4, dtype=torch.float32)
pts = torch.stack(torch.meshgrid(g, g, g, indexing="ij"), -1).reshape(-1, 3)
pts = pts.contiguous().cuda()
d = distCUDA2(pts)
torch.cuda.synchronize()
assert d.shape == (64,), d.shape
assert torch.isfinite(d).all()
# every grid point has >= 3 neighbours at distance 1, so the mean of the
# three nearest squared distances is exactly 1
assert torch.allclose(d, torch.ones_like(d)), d
