# flash-attn: the package's own minimal GPU op, from
# packages/flash-attn/package.yml `verify.op`. Generated by
# scripts/generate_recipes.py; edit package.yml, not this file.
import torch
from flash_attn import flash_attn_func
q = torch.randn(1, 8, 4, 32, dtype=torch.float16, device="cuda")
out = flash_attn_func(q, q, q)
assert out.shape == q.shape, out.shape
