# pyg-lib: the package's own minimal GPU op, from
# packages/pyg-lib/package.yml `verify.op`. Generated by
# scripts/generate_recipes.py; edit package.yml, not this file.
import torch, pyg_lib
from pyg_lib.ops import segment_matmul, sampled_add
x = torch.randn(30, 16, device="cuda")
ptr = torch.tensor([0, 10, 25, 30], device="cuda")
w = torch.randn(3, 16, 8, device="cuda")
out = segment_matmul(x, ptr, w)
ref = torch.cat([x[a:b] @ w[i] for i, (a, b) in enumerate(zip(ptr[:-1].tolist(), ptr[1:].tolist()))])
assert torch.allclose(out, ref, atol=1e-3), (out - ref).abs().max()
a = torch.randn(20, 8, device="cuda"); b = torch.randn(20, 8, device="cuda")
li = torch.randint(0, 20, (50,), device="cuda"); ri = torch.randint(0, 20, (50,), device="cuda")
s = sampled_add(a, b, li, ri)
assert torch.allclose(s, a[li] + b[ri], atol=1e-5), (s - (a[li] + b[ri])).abs().max()
