# torch-generic-nms: the package's own minimal GPU op, from
# packages/torch-generic-nms/package.yml `verify.op`. Generated by
# scripts/generate_recipes.py; edit package.yml, not this file.
import torch
from torch_generic_nms import generic_nms
torch.manual_seed(0)
n = 40
xy = torch.rand(n, 2, device="cuda") * 20
wh = torch.rand(n, 2, device="cuda") * 10 + 2
boxes = torch.cat([xy, xy + wh], 1)
scores = torch.rand(n, device="cuda")
lt = torch.maximum(boxes[:, None, :2], boxes[None, :, :2])
rb = torch.minimum(boxes[:, None, 2:], boxes[None, :, 2:])
inter = (rb - lt).clamp(min=0).prod(-1)
area = wh.prod(-1)
iou = inter / (area[:, None] + area[None, :] - inter)
def ref_nms(iou, scores, thr):
    order = scores.argsort(descending=True).tolist()
    keep = []
    for i in order:
        if all(iou[i, j] <= thr for j in keep):
            keep.append(i)
    return keep
ref = ref_nms(iou, scores, 0.3)
k1 = generic_nms(boxes, scores, 0.3, False).tolist()
k2 = generic_nms(iou, scores, 0.3, True).tolist()
assert k1 == ref, (k1, ref)
assert k2 == ref, (k2, ref)
assert 0 < len(ref) < n, len(ref)
