# cumm: the package's own minimal GPU op, from
# packages/cumm/package.yml `verify.op`. Generated by
# scripts/generate_recipes.py; edit package.yml, not this file.
import numpy as np
from cumm import tensorview as tv
from cumm.nvrtc import CummNVRTCModule
n = 1024
# tv.from_numpy WRAPS the ndarray without copying, so the source must stay
# referenced until .cuda() has read it -- a temporary here is freed first
# and the device copy is garbage (measured: n=8 happened to survive, 1024
# did not).
src_a, src_b = np.arange(n, dtype=np.float32), np.ones(n, dtype=np.float32)
a = tv.from_numpy(src_a).cuda()
assert np.array_equal(a.cpu().numpy(), src_a), "device round-trip"
# pccm reads a Class's source through inspect, so it must live in a real
# module file rather than in this exec'd string.
import importlib.util, os, sys, tempfile, textwrap
path = os.path.join(tempfile.mkdtemp(), "cuw_cumm_op.py")
open(path, "w").write(textwrap.dedent("""
    import pccm
    from cumm.common import TensorViewNVRTC
    class Add(pccm.Class):
        def __init__(self):
            super().__init__()
            self.add_dependency(TensorViewNVRTC)
        @pccm.cuda.cuda_global_function
        def add(self):
            code = pccm.code()
            code.arg("a, b, c", "float*"); code.arg("n", "int")
            code.raw("int i = blockIdx.x * blockDim.x + threadIdx.x; if (i < n) c[i] = a[i] + b[i];")
            return code
"""))
spec = importlib.util.spec_from_file_location("cuw_cumm_op", path)
m = importlib.util.module_from_spec(spec); sys.modules["cuw_cumm_op"] = m; spec.loader.exec_module(m)
mod = CummNVRTCModule([m.Add()], verbose=False)
b = tv.from_numpy(src_b).cuda()
c = tv.zeros([n], tv.float32, 0)
mod.run_kernel("cuw_cumm_op::add", mod.get_launch_param([(n + 255) // 256, 1, 1], [256, 1, 1]), a, b, c, n)
out = c.cpu().numpy()
assert np.array_equal(out, src_a + 1), out[:4]
