"""Turn NVlabs/nvdiffrec's render/ directory into the `nvdiffrec_render` package.

Runs on the fetching machine with cwd = the nvdiffrec checkout, before the
tarball is sealed; one tarball serves every platform, so nothing here branches
on the host and the MSVC/GCC flag choice lives inside the generated setup.py,
which runs on the build machine.

Upstream is a research repo: no setup.py, no version, and its CUDA kernels
(render/renderutils/c_src) are JIT-compiled at first use through
torch.utils.cpp_extension.load, which needs nvcc on the user's machine. This
patch, ported from cuda-wheels with one correction, makes it an installable
package with the kernels compiled ahead of time:

1. render/ becomes nvdiffrec_render/ at the tarball root, and everything else
   in the checkout (train.py, geometry/, dataset/, data/, configs/, docker/,
   images/) is dropped. LICENSE.txt stays.
2. A setup.py is written with ONE CUDAExtension, nvdiffrec_render.renderutils._C,
   built from exactly the seven sources ops.py's _get_plugin() lists. The
   host flags are /O2 or -O3 by os.name at build time.
3. ops.py's _get_plugin() tries `from . import _C` before falling back to the
   JIT path, so an installed wheel never invokes nvcc.
4. THE CORRECTION. The farm's version of this patch copied render/ to
   nvdiffrec_render/nvdiffrec_render/ but left the top directory without an
   __init__.py. setuptools' find_packages() only descends into directories
   that ARE packages, so it found nothing, and the farm's published wheel
   contains the compiled _C and not one .py file -- verified on
   nvdiffrec_render-0.0.1+cu128torch2.8 (linux, win, aarch64: one .so/.pyd
   plus dist-info each). Its consumer does
       from nvdiffrec_render.light import EnvironmentLight
   (TRELLIS.2, trellis2/renderers/pbr_mesh_renderer.py), which that wheel
   cannot satisfy. An empty __init__.py at the top makes find_packages() find
   nvdiffrec_render and nvdiffrec_render.renderutils, and the render modules
   ship. It is empty on purpose: light.py and friends import nvdiffrast at
   module level, and the package must import without it.

Every step asserts on what it found, so an upstream layout change fails here
rather than producing a wheel that is missing something.
"""

import shutil
import sys
from pathlib import Path

PKG = Path("nvdiffrec_render")
SRC = Path("render")
SOURCES = [
    "nvdiffrec_render/renderutils/c_src/mesh.cu",
    "nvdiffrec_render/renderutils/c_src/loss.cu",
    "nvdiffrec_render/renderutils/c_src/bsdf.cu",
    "nvdiffrec_render/renderutils/c_src/normal.cu",
    "nvdiffrec_render/renderutils/c_src/cubemap.cu",
    "nvdiffrec_render/renderutils/c_src/common.cpp",
    "nvdiffrec_render/renderutils/c_src/torch_bindings.cpp",
]
KEEP = {".git", "LICENSE.txt", "README.md", PKG.name, "setup.py"}

SETUP_PY = '''# Generated by cuda-foundry (packages/nvdiffrec-render/patches/nvdiffrec_render.py).
# Upstream NVlabs/nvdiffrec ships no setup.py; render/ is JIT-compiled at
# first use. This builds the same seven sources ahead of time.
import os
from setuptools import setup, find_packages
from torch.utils.cpp_extension import BuildExtension, CUDAExtension

# cl.exe does not error on a GCC flag, it prints D9002 and ships unoptimised;
# decided here, on the build machine, rather than in the fetch-time patch.
cxx_flags = ["/O2", "-DNVDR_TORCH"] if os.name == "nt" else ["-O3", "-DNVDR_TORCH"]

setup(
    name="nvdiffrec_render",
    version="0.0.1",
    description="Render utilities from NVlabs/nvdiffrec for differentiable rendering",
    packages=find_packages(),
    ext_modules=[
        CUDAExtension(
            name="nvdiffrec_render.renderutils._C",
            sources=%s,
            extra_compile_args={"cxx": cxx_flags, "nvcc": ["-O3", "-DNVDR_TORCH"]},
        ),
    ],
    cmdclass={"build_ext": BuildExtension},
    install_requires=["torch", "numpy", "nvdiffrast", "imageio"],
)
''' % repr(SOURCES).replace("', '", "',\n                     '")

OPS_ANCHOR = "    if _cached_plugin is not None:\n        return _cached_plugin\n"
OPS_PATCH = '''
    # cuda-foundry: prefer the ahead-of-time extension shipped in the wheel;
    # the JIT path below is only reached from a source checkout.
    try:
        from . import _C
        _cached_plugin = _C
        return _cached_plugin
    except ImportError:
        pass
'''


def die(msg: str) -> None:
    sys.exit(f"nvdiffrec_render patch: {msg}")


def main() -> None:
    if PKG.is_dir() and not SRC.is_dir():
        if not (PKG / "__init__.py").is_file() or not Path("setup.py").is_file():
            die(f"{PKG} exists but is not a tree this patch produced")
        print("nvdiffrec_render patch: already applied")
        return
    if not (SRC / "renderutils" / "c_src" / "torch_bindings.cpp").is_file():
        die("render/renderutils/c_src/torch_bindings.cpp is missing -- upstream "
            "moved the kernels; re-read the layout at this rev")
    if not Path("LICENSE.txt").is_file():
        die("LICENSE.txt is missing at the repo root")

    shutil.move(str(SRC), str(PKG))
    # The correction described in the module docstring.
    (PKG / "__init__.py").write_text(
        "# nvdiffrec's render/ as an installable package (cuda-foundry). Empty on\n"
        "# purpose: the submodules import nvdiffrast at module level, and this\n"
        "# package must import without it.\n", encoding="utf-8")
    for src in SOURCES:
        if not Path(src).is_file():
            die(f"expected source {src} is missing after the move")
    Path("setup.py").write_text(SETUP_PY, encoding="utf-8")

    ops = PKG / "renderutils" / "ops.py"
    text = ops.read_text(encoding="utf-8")
    if text.count(OPS_ANCHOR) != 1:
        die(f"expected exactly one cached-plugin early return in {ops}, found "
            f"{text.count(OPS_ANCHOR)} -- upstream changed _get_plugin()")
    ops.write_text(text.replace(OPS_ANCHOR, OPS_ANCHOR + OPS_PATCH), encoding="utf-8")

    dropped = 0
    for entry in Path(".").iterdir():
        if entry.name in KEEP:
            continue
        shutil.rmtree(entry) if entry.is_dir() else entry.unlink()
        dropped += 1

    pkgs = {p.parent.relative_to(".").as_posix() for p in PKG.rglob("__init__.py")}
    if pkgs != {"nvdiffrec_render", "nvdiffrec_render/renderutils"}:
        die(f"find_packages() would see {sorted(pkgs)}; expected the package and "
            f"renderutils only")
    print(f"nvdiffrec_render patch: render/ -> {PKG}/ with __init__.py, setup.py "
          f"written, ops.py prefers the AOT extension, {dropped} top-level "
          f"entr(ies) dropped")


if __name__ == "__main__":
    main()
