# vox2seq: the package's own minimal GPU op, from
# packages/vox2seq/package.yml `verify.op`. Generated by
# scripts/generate_recipes.py; edit package.yml, not this file.
import torch, vox2seq
c = torch.randint(0, 1024, (4096, 3), device="cuda", dtype=torch.int32)
for mode in ("z_order", "hilbert"):
    code = vox2seq.encode(c, mode=mode)
    back = vox2seq.decode(code, mode=mode)
    assert torch.equal(back.int(), c), mode
# The pure-torch reference (upstream's own test.py) agrees with the kernels.
for mode in ("z_order", "hilbert"):
    assert torch.equal(vox2seq.encode(c, mode=mode), vox2seq.pytorch.encode(c, mode=mode)), mode
